# SPDX-FileCopyrightText: 2018 GitHub, Inc. and contributors
#
# SPDX-License-Identifier: MIT

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: "web-ext-artifacts/custom_doi_resolver-*.zip"
