# SPDX-FileCopyrightText: 2018 GitHub, Inc. and contributors
#
# SPDX-License-Identifier: MIT

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: "web-ext-artifacts/custom_doi_resolver-*.zip"
